### ISSUE TITLE
reduce required data.table version to 1.12.0?

### ISSUE THREAD

**Issue by elindie** [metrotransit/speedrt#12]
```
install_github('metrotransit/speedrt@develop')
```
requires `data.table` 1.12.2 which is not available on CRAN. Compiling binary throws an error in Mac not properly configured (though @botanize you helped figure this out in https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac).

Wonder whether falling back to CRAN package hurts anything in particular about speedRT given the likelihood of end users not being bleeding edge with `data.table`. Just a thought.

**Comment by botanize** [comment]
Current release on [CRAN](https://rweb.crmda.ku.edu/cran/web/packages/data.table/) is 1.12.2, not sure why you're only seeing 1.12.0.
